char login_html[] =
"<html>\r\n"
"<head>\r\n"
"    <title>AMMYY Router - Login</title>\r\n"
"</head>\r\n"
"<body>	\r\n"
"	<table>\r\n"
"	<tr>\r\n"
"	<td align=\"center\"><b>Ammyy Router</b></td>\r\n"
"	</tr>\r\n"
"	<tr>\r\n"
"	<td width=\"300px\" align=\"center\" valign=\"middle\">\r\n"
"	<form method=\"GET\" action=\"/\">\r\n"
"	Password: <input type=\"password\" name=\"psw\">\r\n"
"	<input type=\"submit\" value=\"Sign in\">\r\n"
"	</form>\r\n"
"	</td>\r\n"
"	</tr>\r\n"
"	</table>\r\n"
"</body>\r\n"
"</html>";
