//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Installer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_PERMISSION_LIST             132
#define IDD_OPERATOR_PERMISSION         133
#define IDD_SETTINGS                    138
#define IDD_SETTINGS_COMMON             138
#define IDD_ADD_COMPUTER                139
#define IDR_MENU1                       140
#define IDD_CONTACT_BOOK                148
#define IDD_HTTP_PROXY                  149
#define IDR_CUSTOMIZE                   150
#define IDD_RDP_SETTINGS                152
#define IDD_SETTINGS_NETWORK            154
#define IDD_PASSWORD_INPUT              159
#define IDD_SETTINGS_OPERATOR           160
#define IDD_SETTINGS_CLIENT             161
#define IDD_DIRECT_IN                   162
#define IDD_EXTERNAL_PORTS              162
#define IDD_SPEED_TEST                  163
#define IDB_CONTACKBOOK_0               164
#define IDB_CONTACKBOOK_1               165
#define IDB_CONTACKBOOK_2               166
#define IDB_CONTACKBOOK_3               167
#define IDD_ENCODER                     168
#define IDD_ENCODER_LIST                169
#define IDB_IMPORT                      171
#define IDB_EXPORT                      172
#define IDD_TR_ACCEPT                   173
#define IDD_VR_OPTION1                  174
#define IDACCEPT                        1030
#define IDREJECT                        1031
#define IDC_ACCEPT_CONN_TEXT            1107
#define IDC_REMEMBER                    1108
#define IDC_VIEW_SCREEN                 1110
#define IDC_REMOTE_CONTROL              1111
#define IDC_ENABLE_FS                   1112
#define IDC_AUDIO_CHAT                  1113
#define IDC_RDP_SESSION                 1114
#define IDC_STATIC_DISPLAY              1115
#define IDC_STATIC_SCALE                1116
#define IDC_SCALE_EDIT                  1117
#define IDC_STATIC_P                    1118
#define IDC_FULLSCREEN                  1119
#define IDC_AUTO_SCROLL_WND_MODE        1120
#define IDC_REMOTE_CURSOR               1121
#define IDC_LOCAL_CURSOR                1122
#define IDC_LOAD                        1123
#define IDC_SAVE                        1124
#define IDC_CONNECTION_INFO             1125
#define IDB_INSTALL                     1500
#define IDB_START_STOP                  1505
#define IDB_STOP                        1506
#define IDB_CONNECT                     1507
#define IDC_YOUR_ID                     1511
#define IDC_ROUTER                      1517
#define IDC_ADD                         1518
#define IDC_PERMISSIONS                 1518
#define IDC_AMMYY_VERSION               1527
#define IDC_BUILD_TIME                  1528
#define IDC_PC_LIST                     1530
#define IDC_REMOVE                      1531
#define IDC_PERMISSION                  1536
#define IDC_COMPUTER_ID                 1537
#define IDC_ROUTER_TYPE                 1538
#define IDC_ROUTER_TEXT                 1539
#define IDC_FILES_FOLDER                1542
#define IDC_REQUEST_ROUTER              1543
#define IDC_DELETE_FILES                1545
#define IDC_WARN_FULL_SCREEN            1548
#define IDC_OFF_BACKGROUND              1552
#define IDC_CAPTURE_HINTS               1553
#define IDC_COMPUTER_ALIAS              1554
#define IDC_ADDRESS                     1554
#define IDC_LIST                        1556
#define IDC_UP                          1558
#define IDC_DOWN                        1559
#define IDC_CONNECT                     1560
#define IDC_PORT                        1564
#define IDC_USERNAME                    1565
#define IDC_PASSWORD                    1566
#define IDC_HTTP_PROXY                  1567
#define IDC_LINK                        1568
#define IDC_LINK_CUSTOM                 1569
#define IDC_DISABLE_THEMES              1569
#define IDC_DISABLE_MENU_ANIM           1570
#define IDC_DISABLE_WALLPAPER           1571
#define IDC_DISABLE_FULL_WND_DRAG       1572
#define IDC_WIDTH                       1573
#define IDC_HEIGHT                      1574
#define IDC_BPP                         1575
#define IDC_SOUND_MODE                  1576
#define IDC_RDP_SETTINGS                1577
#define IDC_SCREEN_MODE                 1578
#define IDC_AUDIO_PLAY                  1579
#define IDC_AUDIO_RECD                  1580
#define IDC_DEBUG_LOG                   1581
#define IDC_RUN_SYSTEM_VISTA            1582
#define IDC_EXPORT                      1584
#define IDC_IMPORT                      1585
#define IDC_PASSWORD1                   1587
#define IDC_PASSWORD2                   1588
#define IDC_EDIT                        1596
#define IDC_PROTECT_SETTINGS            1598
#define IDC_STATIC1                     1602
#define IDC_USE_PROXY                   1603
#define IDC_IE_ADDRESS                  1604
#define IDC_IE_PORT                     1605
#define IDC_SET_IE_PROXY                1608
#define IDC_OFF_VISUAL_EFFECTS          1612
#define IDC_OFF_COMPOSITION             1613
#define IDC_ACCESS_FILES                1614
#define IDC_START_CLIENT                1615
#define IDC_ENCRYPTION                  1616
#define IDC_YOUR_IP                     1617
#define IDC_USE_WAN                     1619
#define IDC_ROUTER_STATIC               1620
#define IDC_INCOMING_LAN                1625
#define IDC_PORT_STATIC                 1626
#define IDC_DIRECT_IN                   1627
#define IDC_EXTERNAL_TCP_PORTS          1627
#define IDC_LIST1                       1628
#define IDC_CHECK                       1629
#define IDC_DIRECT_TCP                  1633
#define IDC_TEXT                        1634
#define IDC_START                       1635
#define IDC_STATUS                      1637
#define IDC_TIME                        1638
#define IDC_CLEAR                       1639
#define IDC_FOLDER                      1640
#define IDC_LABEL_ID                    1641
#define IDC_DESCRIPTION                 1642
#define IDC_COPY_FILE_TIME              1643
#define IDC_COLOR_QUALITY               1644
#define IDC_STATIC_ENCODING             1645
#define IDC_ENCODING                    1646
#define IDC_COMPRESSLEVEL_TEXT          1647
#define IDC_STATIC_FAST                 1648
#define IDC_STATIC_BEST                 1649
#define IDC_COMPRESSLEVEL               1650
#define IDC_JPEG_TEXT                   1651
#define IDC_STATIC_JPEG1                1652
#define IDC_STATIC_JPEG2                1653
#define IDC_QUALITYLEVEL                1654
#define IDC_TEXT_DESCR                  1657
#define IDC_SET_DEFAULT                 1658
#define IDC_ENCODER_LIST                1659
#define IDC_STATIC_COPYRIGHT            1660
#define ID_LANGUAGE_ENGLISH             32771
#define ID_LANGUAGE_LAST                32870
#define ID_HELP_AMMYY_WEBSITE           32884
#define ID_HELP_ABOUT                   32885
#define ID_MENU_SETTINGS                32886
#define ID_MENU_EXIT                    32887
#define ID_SERVICE_INSTALL              32889
#define ID_SERVICE_START                32890
#define ID_SERVICE_STOP                 32891
#define ID_SERVICE_REMOVE               32892
#define ID_MENU_CONTACTBOOK             32893

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32894
#define _APS_NEXT_CONTROL_VALUE         1662
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
